### PR TITLE
feat(pause-hive-sync): now can check the status of the pausing

### PR DESCRIPTION
**Pull request by georgettica**
Add the ability to verify if a hive-sync is enabled or disabled.

This was missing as I wanted to check if the hive-sync is enabled

### CODE REVIEW

**Comment by iamkirkbater** [comment]
Is there any reason this script needs to be ocm-container specific?  This would probably be better off in ops-sop.

**Comment by fahlmant** [comment]
Please add a description

**Comment by georgettica** [comment]
@fahlmant done as requested

**Comment by clcollins** [comment]
I'm going to move this to ops-sop as @iamkirkbater suggested.  I'll follow up with a PR here to remove the script in ocm-container when the ops-sop PR merges.

/close

**Pull request closed without merging**
