### PR TITLE
georgettica/make ocm login automatic

### PR DESCRIPTION
**Pull request by georgettica**
- Create update_deps.yml
- feat(bashrc): make ocm-login automatic

### CODE REVIEW

**Comment by clcollins** [comment]
The auto-login is fine, no issues with that.

I don't think thr GitHub Actions will work in OpenShift org repos, though.  Apparently it's a legacy account or something.

**Comment by georgettica** [comment]
Damn, it keeps popping up!
Annoying :(

**Comment by georgettica** [comment]
I need to be more careful next time :)

**Comment by georgettica** [comment]
@clcollins I changed the PR to be `the ocm login command but faster`

you can TAL whenever you see fit

**Pull request merged**
