### PR TITLE
Fixes bash prompt

### PR DESCRIPTION
**Pull request by clcollins**
There was an issue possibly introduced in #62 caused by non-printing characters that is causing the prompt to be unaware of it's length.  This is causing pasted or lines scrolled through the history to have inconsistent placement and unpredictable behavior.

 This fix should keep the same prompt layout and colors, but fix the non-printing character issue.

Signed-off-by: Christopher Collins <collins.christopher@gmail.com>

### CODE REVIEW

**Comment by georgettica** [comment]
seems this makes the `kube-ps1` to not show up.. any idea why?

**Comment by clcollins** [comment]
@georgettica Good catch. I think I dropped a `\` before the `$(kube_ps1)`. Mind trying again?

**Comment by georgettica** [comment]
Works ok, building with no cache now to verify

**Comment by georgettica** [comment]
Works :)

**Pull request merged**
