### PR TITLE
Installs and uses backplane-tools for other tool installations

### PR DESCRIPTION
**Pull request by clcollins**
Installs and uses backplane-tools for other tool installations

This PR adds backplane-tools to ocm-container, and uses it to install
the core tools that it manages, replacing the existing installers.

Signed-off-by: Chris Collins <collins.christopher@gmail.com>

### CODE REVIEW

**Comment by clcollins** [comment]
/hold 

Unsure if this will work without backplane-tools specifiying versions on install, or a nightly build in Quay (which I don't think exists)

**Comment by T0MASD** [comment]
I have verfied this works pretty well, can you please rebase it on top of the latest master and let's use this method to update to latest deps going forward

**Comment by clcollins** [comment]
@T0MASD - rebased as requested.

Will this work properly with the image builds?

**Comment by T0MASD** [comment]
I've tested this branch in: https://quay.io/repository/todabasi_openshift/ocm-container/build/4596e872-34c0-4efc-9ddc-91927a98e301
```
 11/6/2023, 9:50:57 AM ---> Running in dcbaac85427e
11/6/2023, 9:50:57 AM Installing the following tools: - aws - ocm - osdctl - backplane-cli - rosa
11/6/2023, 9:50:57 AM Installing aws
11/6/2023, 9:51:00 AM Successfully installed aws
11/6/2023, 9:51:00 AM
11/6/2023, 9:51:00 AM Installing ocm
11/6/2023, 9:51:00 AM Successfully installed ocm Installing osdctl
11/6/2023, 9:51:02 AM Successfully installed osdctl Installing backplane-cli
11/6/2023, 9:51:03 AM Successfully installed backplane-cli Installing rosa
11/6/2023, 9:51:04 AM Successfully installed rosa
11/6/2023, 9:51:25 AM Removing intermediate container dcbaac85427e
11/6/2023, 9:51:25 AM ---> 69c3f6ba8eeb 
```

and using this locally

/unhold
/lgtm

**Pull request merged**
