### PR TITLE
Add servielogger

### PR DESCRIPTION
**Pull request by rendhalver**
Add servicelogger

### CODE REVIEW

**Comment by rendhalver** [comment]
/hold
Need to split out the backplane-tools update/

**Comment by clcollins** [comment]
@rendhalver the tests are unblocked for now. Do you want to rebase and finish this one up?

**Comment by rendhalver** [comment]
> @rendhalver the tests are unblocked for now. Do you want to rebase and finish this one up?

@clcollins  Done!
Ready for a review.

**Pull request merged**
