### PR TITLE
Setup repo for Prow builds of golang cli

### PR DESCRIPTION
**Pull request by rendhalver**

### CODE REVIEW

**Comment by rendhalver** [comment]
openshift/release#51386 will be needed for this to work properly.
Not sure which order these need to be merged in though.

**Comment by clcollins** [comment]
https://github.com/openshift/release/pull/51386 Looks like it's failing tests

**Comment by clcollins** [comment]
/retest

#ONEMORETIME!

**Comment by clcollins** [comment]
/hold

...for https://github.com/openshift/release/pull/51386 to be merged

**Pull request closed without merging**
