### PR TITLE
Update tools

### PR DESCRIPTION
**Pull request by rendhalver**
Update osdctl, ocm, and rosa to latest releases

### CODE REVIEW

**Comment by Tof1973** [comment]
If updating versions in container, we could also update:

-ARG YQ_VERSION="tags/v4.31.1"
+ARG YQ_VERSION="tags/v4.35.2"

-ARG JIRA_VERSION="tags/v1.3.0"
+ARG JIRA_VERSION="tags/v1.4.0"

**Comment by rendhalver** [comment]
Adding suggested updates
/hold

**Pull request merged**
