### PR TITLE
Adds some error handling/more detail to create-cluster script

### PR DESCRIPTION
**Pull request by clcollins**
Adds some more verbose output in the event of an error creating a
cluster with the `create-cluster` script.

Signed-off-by: Christopher Collins <collins.christopher@gmail.com>

### CODE REVIEW

**Comment by georgettica** [comment]
Seems fairly straightforward..
I think this script is maintained also in another repo @cblecker s maybe?
If so did you also longer there regarding this change?

If not it's fine and it can be merged.

Will test it tomorrow

**Comment by georgettica** [comment]
seems to work. approving

**Comment by clcollins** [comment]
@georgettica Just FYI, I wrote this script specifically for ocm-container.  If it exists elsewhere now, I'm not aware of it.

**Comment by georgettica** [comment]
I was incorrect, thought it was sre-login

**Pull request merged**
