### PR TITLE
[create-pull-request] automated change

### PR DESCRIPTION
**Pull request by georgettica**

### CODE REVIEW

**Comment by clcollins** [comment]
/lgtm

This is some awesome automation here.  We might consider adding it directly to this repo?

**Comment by georgettica** [comment]
That depends on other gods to do that, please get approval as some Don't like two ci systems (prow is the main one)

**Comment by georgettica** [comment]
I guess we should get approval before merging (as this incurs the automation I was doing

**Comment by georgettica** [comment]
I didn't see we added this!
Will promptly add the version bumps automation

**Pull request merged**
