### PR TITLE
feat(automation): add GH release updates

### PR DESCRIPTION
**Pull request by georgettica**
- the github action has comments to explain what is going on
- Dockerfile was changed to make verifying what changed in the release easier
- sorted github releases in dockerfile
- added a short explanation on each binary we add
- runs on a daily cronjob

### CODE REVIEW

**Comment by georgettica** [comment]
closes https://github.com/openshift/ocm-container/pull/92

**Comment by T0MASD** [comment]
Not a big deal, but var names TOOL_SHORT_URL could be renamed as TOOL_URL_SLUG

**Comment by georgettica** [comment]
done @T0MASD

**Comment by georgettica** [comment]
if this is not acceptable, I'll add this repo to openshift/release and put the script there. I started checking how to add the credentials

**Comment by georgettica** [comment]
Ok, so I'll close the PR and make another with changes that will make it easier for me later

**Comment by georgettica** [comment]
@rafael-azevedo 
See PR https://github.com/georgettica/ocm-container/pull/76

**Pull request closed without merging**
