### PR TITLE
add yum-utils and disable google repo

### PR DESCRIPTION
**Pull request by T0MASD**
add yum-utils and disable google repo after gcloud install as it is often source of timeouts when building on top of ocm-container in the future

### CODE REVIEW

**Comment by iamkirkbater** [comment]
Are these related to daily ops tasks? I think adding these tools might be a bit too far of a deviation from the spirit of ocm-container, which is mainly to provide a stable, reproducible environment for SREs to access clusters and perform operations-related tasks.

I think running terraform tasks and packer operations falls outside of that scope.

I'm putting a hold on this for further discussion though.

/hold

**Comment by T0MASD** [comment]
I've updated the PR to essentially disable google-cloud-sdk repo after the container build as it is often source of time outs for follow up builds

**Comment by clcollins** [comment]
/lgtm

With the yum-utils and google-sdk changes, minus the others. :+1:

**Pull request merged**
